spring:
  profiles:
    group:
      local:
        - local-mysql
        - api
        - oauth
        - token
        - actuator
      dev:
        - mysql
        - api
        - oauth
        - token
        - log
        - actuator
      prod:
        - mysql
        - api
        - oauth
        - token
        - log
        - actuator
    active: local