spring:
  profiles:
    group:
      local:
        - local-mysql
        - api
        - oauth
        - local-token
      dev:
        - mysql
        - api
        - oauth
        - token
      prod:
        - mysql
        - api
        - oauth
        - token
    active: local