spring:
  profiles:
    group:
      local:
        - local-mysql
        - local-api
      dev:
        - dev-mysql
        - dev-api
      prod:
        - prod-mysql
        - prod-api
    active: local