spring:
  profiles:
    group:
      local:
        - local-mysql
        - api
        - oauth
        - token
        - actuator
        - local-redis
      dev:
        - mysql
        - api
        - oauth
        - token
        - log
        - actuator
        - redis
      prod:
        - mysql
        - api
        - oauth
        - token
        - log
        - actuator
        - redis
    active: local