spring:
  config:
    activate:
      on-profile: token

security:
  jwt:
    access:
      validTime: ${AT_VALID_TIME}
      secretKey: ${AT_TOKEN_SECRET_KEY}
    refresh:
      validTime: ${RT_VALID_TIME}
      secretKey: ${RT_TOKEN_SECRET_KEY}