# github repository actions 페이지에 나타날 이름
name: Backend CI

# event trigger
# main 브랜치에 push, PR이 되었을 때 workflow 실행
on:
  push:
    branches: [ "main","be","be-release"]
    paths : 'BE/**'
  pull_request:
    branches: [ "main","be","be-release"]
    paths : 'BE/**'

defaults:
  run:
    working-directory: ./BE/eeos

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: JDK 17 설정
      uses: actions/checkout@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: DB를 실행
      run: |
        docker-compose -f resources/local-develop-environment/docker-compose.yml up -d
        sleep 20
      
    - name: Gradle 캐싱
      uses: actions/cache@v3
      with:
        path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
            ${{ runner.os }}-gradle-

    - name: Gradle로 빌드
      run: ./gradlew build

    - name: Github 이벤트 파일 업로드
      uses: actions/upload-artifact@v2
      with:
        name: Event File
        path: ${{ github.event_path }}

    - name: 단위 테스트 파일 결과 업로드
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results
        path: |
          '**/build/test-results/test/TEST-*.xml'

    - name: 테스트 실패 시, 실패한 코드 라인에 Check 코멘트를 등록
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
        token: ${{ github.token }}
        skip-if-no-changes: true
        min-coverage-overall: 70
        min-coverage-changed-files: 50
